spring.application.name=ex15-fileupload

# 포트설정
server.port=8282

# Spring Boot Dashboard가 실행 포트를 인식하도록 JMX 활성화
spring.jmx.enabled=true
spring.application.admin.enabled=true

# 파일업로드를 위한 multipart 설정
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=20MB