spring.application.name=ex14-security-jdbc

# 포트설정
server.port=8282

# oracle 접속정보 설정
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1523/XEPDB1
spring.datasource.username=boot_user
spring.datasource.password=1234

# Spring Boot Dashboard가 실행 포트를 읽으려면 JMX가 필요합니다.
spring.jmx.enabled=true
spring.application.admin.enabled=true
