spring.application.name=ex09-transaction-manager

# 포트설정
server.port=8282

# oracle 접속정보 설정
# spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XEPDB1

spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.url=jdbc:log4jdbc:oracle:thin:@localhost:1523/XEPDB1

spring.datasource.username=boot_user
spring.datasource.password=1234

# mybatis 메퍼의 위치설정(src/main/resources 하위에 폴더(패키지) 생성 후 파일 생성)
# mapper 폴더 생성 후 BoardDAO.xml 파일 생성
mybatis.mapper-locations=classpath:mapper/**/**.xml

# Windows 콘솔(CP949)과 맞춰 로그 한글 깨짐 방지
# logging.charset.console=MS949
