spring.application.name=ex17-spring-data-jpa1

# 포트설정
server.port=8282

# oracle 접속정보 설정
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1523/XEPDB1
spring.datasource.username=boot_user
spring.datasource.password=1234

#  JPA 설정
spring.jpa.properties.hibernate.platform=org.hibernate.dialect.Oracle12cDialect
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
# none: 테이블 생성 안함, create: 테이블 생성, update: 테이블 수정, create-drop: 테이블 생성 후 삭제
# update: 테이블 수정
#   새로운 컬럼이 추가될때만 적용되고, 변경, 삭제, 타입변경은 적용안됨.
# create-drop: 테이블 생성 후 삭제
# create: 테이블 생성
# validate: 테이블 생성 후 삭제
# 권장사항 : 첫 실행은 create, 이후 update로 변경
spring.jpa.properties.hibernate.hbm2ddl.auto=none

# show sql data binding
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=trace
