spring.application.name=ex15-fileupload

# 포트설정
server.port=8282

# Spring Boot Dashboard가 실행 포트를 인식하도록 JMX 활성화
spring.jmx.enabled=true
spring.application.admin.enabled=true

# 파일업로드를 위한 multipart 설정
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=20MB

# oracle 접속 정보
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1523/XEPDB1
spring.datasource.username=boot_user
spring.datasource.password=1234

# mybatis 매퍼 위치 설정
mybatis.mapper-locations=classpath:mapper/**/*.xml