spring.application.name=ex16-restapi

# 포트설정
server.port=8282

# IDE(Spring Boot Dashboard)가 실행 포트를 인식하도록 JMX 활성화
spring.jmx.enabled=true
spring.application.admin.enabled=true

# oracle 접속 정보 설정
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1523/XEPDB1
spring.datasource.username=boot_user
spring.datasource.password=1234

# mybatis 매퍼의 위치 설정
mybatis.mapper-locations=classpath:/mapper/**/**.xml

# 페이징을 위한 설정값
board.pageSize=3
board.blockPage=3

